package dao;

import model.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;

import javax.sql.DataSource;
import java.sql.*;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
class UserDAOImplTest {

    @Mock private DataSource dataSource;
    @Mock private Connection connection;
    @Mock private PreparedStatement pstmt;
    @Mock private ResultSet rs;

    private UserDAOImpl userDAO;

    @BeforeEach
    void setUp() throws Exception {
        userDAO = new UserDAOImpl(dataSource);
        when(dataSource.getConnection()).thenReturn(connection);
    }

    // ==================== REGISTER ====================
    @Test
    void register_InsertsUserAndSetsId() throws Exception {
        // Dùng anyInt() cho tham số autoGeneratedKeys để tránh warning
        when(connection.prepareStatement(anyString(), anyInt())).thenReturn(pstmt);
        when(pstmt.executeUpdate()).thenReturn(1);
        when(pstmt.getGeneratedKeys()).thenReturn(rs);
        when(rs.next()).thenReturn(true);
        when(rs.getInt(1)).thenReturn(42);

        User user = new User("Real", "user1", "e@mail", "pass", "0123");
        assertTrue(userDAO.register(user));
        assertEquals(42, user.getID());
    }

    @Test
    void register_Fails_ReturnsFalse() throws Exception {
        when(connection.prepareStatement(anyString(), anyInt())).thenReturn(pstmt);
        when(pstmt.executeUpdate()).thenReturn(0);

        User user = new User("Real", "user1", "e@mail", "pass", "0123");
        assertFalse(userDAO.register(user));
        assertEquals(0, user.getID());
    }

    // ==================== LOGIN ====================
    @Test
    void login_ValidCredentials_ReturnsUser() throws Exception {
        when(connection.prepareStatement(anyString())).thenReturn(pstmt);
        when(pstmt.executeQuery()).thenReturn(rs);
        when(rs.next()).thenReturn(true);
        mockUserResultSet(rs, 1, "user", "pass", "Real", "e@mail", "0123", User.Role.USER, 100.0, 0.0);

        User result = userDAO.login("user", "pass");
        assertNotNull(result);
        assertEquals("user", result.getUsername());
    }

    @Test
    void login_InvalidPassword_ReturnsNull() throws Exception {
        when(connection.prepareStatement(anyString())).thenReturn(pstmt);
        when(pstmt.executeQuery()).thenReturn(rs);
        when(rs.next()).thenReturn(false);

        assertNull(userDAO.login("user", "wrong"));
    }

    // ==================== getUserById ====================
    @Test
    void getUserById_Found() throws Exception {
        when(connection.prepareStatement(anyString())).thenReturn(pstmt);
        when(pstmt.executeQuery()).thenReturn(rs);
        when(rs.next()).thenReturn(true);
        mockUserResultSet(rs, 1, "u", "p", "R", "e", "0123", User.Role.USER, 200, 50);

        User u = userDAO.getUserById(1);
        assertNotNull(u);
        assertEquals(200.0, u.getBalance());
        assertEquals(50.0, u.getFrozenBalance());
    }

    @Test
    void getUserById_NotFound() throws Exception {
        when(connection.prepareStatement(anyString())).thenReturn(pstmt);
        when(pstmt.executeQuery()).thenReturn(rs);
        when(rs.next()).thenReturn(false);

        assertNull(userDAO.getUserById(999));
    }

    // ==================== deductFrozenMoneyAtomic ====================
    @Test
    void deductFrozenMoneyAtomic_Success() throws Exception {
        when(connection.prepareStatement(anyString())).thenReturn(pstmt);
        when(pstmt.executeUpdate()).thenReturn(1);

        assertTrue(userDAO.deductFrozenMoneyAtomic(connection, 1, 100));
        verify(pstmt).setDouble(1, 100);
        verify(pstmt).setInt(2, 1);
        verify(pstmt).setDouble(3, 100);
    }

    @Test
    void deductFrozenMoneyAtomic_Insufficient_ReturnsFalse() throws Exception {
        when(connection.prepareStatement(anyString())).thenReturn(pstmt);
        when(pstmt.executeUpdate()).thenReturn(0);

        assertFalse(userDAO.deductFrozenMoneyAtomic(connection, 1, 999999));
    }

    @Test
    void deductFrozenMoneyAtomic_AutoConnection_Success() throws Exception {
        when(dataSource.getConnection()).thenReturn(connection);
        when(connection.prepareStatement(anyString())).thenReturn(pstmt);
        when(pstmt.executeUpdate()).thenReturn(1);

        assertTrue(userDAO.deductFrozenMoneyAtomic(1, 50));
        verify(connection).close();
    }

    // ==================== refundMoneyAtomic ====================
    @Test
    void refundMoneyAtomic_UpdatesBalance() throws Exception {
        when(connection.prepareStatement(anyString())).thenReturn(pstmt);
        when(pstmt.executeUpdate()).thenReturn(1);

        assertTrue(userDAO.refundMoneyAtomic(connection, 2, 75));
    }

    // ==================== addMoneyAtomic ====================
    @Test
    void addMoneyAtomic_UpdatesBalance() throws Exception {
        when(connection.prepareStatement(anyString())).thenReturn(pstmt);
        when(pstmt.executeUpdate()).thenReturn(1);

        assertTrue(userDAO.addMoneyAtomic(connection, 3, 200));
    }

    // ==================== freezeMoneyAtomic ====================
    @Test
    void freezeMoneyAtomic_SufficientBalance() throws Exception {
        when(connection.prepareStatement(anyString())).thenReturn(pstmt);
        when(pstmt.executeUpdate()).thenReturn(1);

        assertTrue(userDAO.freezeMoneyAtomic(connection, 1, 100));
    }

    @Test
    void freezeMoneyAtomic_InsufficientBalance() throws Exception {
        when(connection.prepareStatement(anyString())).thenReturn(pstmt);
        when(pstmt.executeUpdate()).thenReturn(0);

        assertFalse(userDAO.freezeMoneyAtomic(connection, 1, 9999));
    }

    // ==================== updateStatus ====================
    @Test
    void updateStatus_UpdatesRow() throws Exception {
        when(connection.prepareStatement(anyString())).thenReturn(pstmt);
        when(pstmt.executeUpdate()).thenReturn(1);

        assertTrue(userDAO.updateStatus(connection, 1, "ACTIVE"));
    }

    @Test
    void updateStatus_NoRowAffected() throws Exception {
        when(connection.prepareStatement(anyString())).thenReturn(pstmt);
        when(pstmt.executeUpdate()).thenReturn(0);

        assertFalse(userDAO.updateStatus(connection, 999, "BANNED"));
    }

    // ==================== getAllUsers ====================
    @Test
    void getAllUsers_ReturnsList() throws Exception {
        when(dataSource.getConnection()).thenReturn(connection);
        when(connection.prepareStatement(anyString())).thenReturn(pstmt);
        when(pstmt.executeQuery()).thenReturn(rs);
        when(rs.next()).thenReturn(true, true, false);
        mockUserResultSet(rs, 1, "a", "p", "A", "a@t", "0", User.Role.USER, 100, 0);
        when(rs.getInt("id")).thenReturn(1, 2);
        when(rs.getString("username")).thenReturn("a", "b");
        when(rs.getString("password")).thenReturn("p1", "p2");
        when(rs.getString("real_name")).thenReturn("A1", "A2");
        when(rs.getString("email")).thenReturn("e1", "e2");
        when(rs.getString("phone_number")).thenReturn("01", "02");
        when(rs.getString("role")).thenReturn("USER", "ADMIN");
        when(rs.getDouble("balance")).thenReturn(100.0, 200.0);
        when(rs.getDouble("frozen_balance")).thenReturn(0.0, 50.0);

        assertEquals(2, userDAO.getAllUsers().size());
    }

    // ==================== searchUsers ====================
    @Test
    void searchUsers_FindsMatches() throws Exception {
        when(dataSource.getConnection()).thenReturn(connection);
        when(connection.prepareStatement(anyString())).thenReturn(pstmt);
        when(pstmt.executeQuery()).thenReturn(rs);
        when(rs.next()).thenReturn(true, false);
        when(rs.getInt("id")).thenReturn(1);
        when(rs.getString("username")).thenReturn("john");
        when(rs.getString("password")).thenReturn("p");
        when(rs.getString("real_name")).thenReturn("John");
        when(rs.getString("email")).thenReturn("j@t");
        when(rs.getString("phone_number")).thenReturn("0");
        when(rs.getString("role")).thenReturn("USER");
        when(rs.getDouble("balance")).thenReturn(0.0);
        when(rs.getDouble("frozen_balance")).thenReturn(0.0);

        assertEquals(1, userDAO.searchUsers("john").size());
    }

    // ========== Helper ==========
    @SuppressWarnings("SameParameterValue")
    private void mockUserResultSet(ResultSet rs, int id, String username, String password,
                                   String realName, String email, String phone,
                                   User.Role role, double balance, double frozen) throws SQLException {
        when(rs.getInt("id")).thenReturn(id);
        when(rs.getString("username")).thenReturn(username);
        when(rs.getString("password")).thenReturn(password);
        when(rs.getString("real_name")).thenReturn(realName);
        when(rs.getString("email")).thenReturn(email);
        when(rs.getString("phone_number")).thenReturn(phone);
        when(rs.getString("role")).thenReturn(role.name());
        when(rs.getDouble("balance")).thenReturn(balance);
        when(rs.getDouble("frozen_balance")).thenReturn(frozen);
    }
}