name: Java CI

on:
  push:
    branches: [ "main", "Merging-safe" ]
  pull_request:
    branches: [ "main", "Merging-safe" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: CheckStyle
        run: mvn checkstyle:check

      - name: Test
        run: mvn test -Dcheckstyle.skip=true -Dmaven.test.failure.ignore=true

      - name: Package
        run: mvn package -DskipTests

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: auction-system-${{ matrix.os }}
          path: target/*.jar

      - name: Upload JaCoCo Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-${{ matrix.os }}
          path: target/site/jacoco/
